### ISSUE TITLE
Not-tech-related Question: Why this name

### ISSUE THREAD

**Issue by dubiao** [codemotionapps/react-native-dynamic#1]
By helping coders to use drak mode, why not keep useing 'dark-mode' name? That is more suitable with the purpose of this repostory, isn't it?

---

By the way, your work helped me a lot. There are many bugs in RN-0.62 `Appearance`.

**Comment by dubiao** [comment]
And, please, can you change the link that mentioned in the `dark mode` repo's [README.md](https://github.com/codemotionapps/react-native-dark-mode/blob/master/README.md) to this github repo? It is now linked to npm page. Link to github page is better, I think.
![image](https://user-images.githubusercontent.com/4001793/85207213-ce21bc00-b359-11ea-80d5-de0c2cc3d32c.png)

**Comment by dimitarnestorov** [comment]
> By helping coders to use drak mode, why not keep useing 'dark-mode' name?

To use dark mode you don't need to use `react-native-dark-mode` anymore. It would be misleading.

A lot of people will also upgrade without reading the changelog, break half their app and then open issues again without reading it.

One more reason would be uniformity, since in the `Appearance` API the concept is called color scheme, and the hook is called `useColorScheme`, I wanted to stay away from the dark mode naming and just use color scheme, `useDarkMode` sounds cool though.

Initially I wanted to call it `react-native-dynamic-stylesheet` but that is taken and with the changes npm made a while ago I can't use `react-native-dynamic-style-sheet` for example. Then I figured out that I also have dynamic values, so technically you could use this without the stylesheet part. I don't really care about the name, this is just a module that we use at work and I'm sharing with the world in case someone finds it useful.

> By the way, your work helped me a lot. There are many bugs in RN-0.62 `Appearance`.

Glad to hear that! After looking at the inner workings of `useColorScheme` I was confused as to why aren't they using context but rather setup a subscription every time you use the hook, even though we mentioned it in the discussion prior to the creation of the `Appearance` API.

> And, please, can you change the link that mentioned in the dark mode repo's README.md to this github repo?

Done. 🙂
